inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  CacheRootDirectory: 'tmp/rubocop_cache/'
  MaxFilesInCache: 50000
  Exclude:
    - 'db/seeds/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Capybara/FeatureMethods:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 372
  Exclude:
    - 'spec/*/*'
    - 'spec/*/*/*'

Metrics/AbcSize:
  Max: 400

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/MethodLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 100

Metrics/ModuleLength:
  Max: 600

Naming/VariableNumber:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
    - 'spec/rails_helper.rb'
