defaults: &defaults
  working_directory: ~/webpagewatcher
  docker:
    - image: circleci/ruby:2.6.2

version: 2
jobs:
  git-checkout:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p ~/webpagewatcher/tmp/test-results

  bundle-install:
    <<: *defaults

  rubocop:
    <<: *defaults
    steps:
      - run: mkdir -p ~/webpagewatcher/tmp/test-results/rubocop
      - run: bundle exec rubocop -R -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb --format RuboCop::Formatter::JUnitFormatter --out ~/webpagewatcher/tmp/test-results/rubocop/rubocop.xml

  bundler-audit:
    <<: *defaults
    steps:
      - run: bundle exec bundler-audit check --update

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # UTC timezone, https://crontab.guru
          filters:
            branches:
              only:
                - master
    jobs:
      - git-checkout
      - bundle-install:
          requires:
            - git-checkout
      - bundler-audit:
          requires:
            - bundle-install

  ci-workflow:
    jobs:
      - git-checkout
      - bundle-install:
          requires:
            - git-checkout
      - rubocop:
          requires:
            - bundle-install
      - bundler-audit:
          requires:
            - bundle-install
