defaults: &defaults
  working_directory: ~/webpagewatcher
  docker:
    - image: circleci/ruby:2.6.2

shared_job_steps:
  - &restore_checkout_cache
    restore_cache:
      key: webpagewatcher-repo-v1.1-{{ .Environment.CIRCLE_SHA1 }}
  - &save_checkout_cache
    save_cache:
      key: webpagewatcher-repo-v1.1-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - ~/webpagewatcher
        - ~/.ssh
  - &restore_bundle_cache
    restore_cache:
      key: webpagewatcher-bundle-v1.1-{{ checksum "Gemfile.lock" }}
  - &save_bundle_cache
    save_cache:
      key: webpagewatcher-bundle-v1.1-{{ checksum "Gemfile.lock" }}
      paths:
        - ~/webpagewatcher/vendor/bundle
  - &bundle_path
    run: bundle --path vendor/bundle
  - &store_test_results
    store_test_results:
      path: ~/webpagewatcher/tmp/test-results
  - &restore_rubocop_cache
    restore_cache:
      key: webpagewatcher-rubocop-v1.1-{{ checksum "Gemfile.lock" }}
  - &save_rubocop_cache
    save_cache:
      key: webpagewatcher-rubocop-v1.1-{{ checksum "Gemfile.lock" }}
      paths:
        - ~/webpagewatcher/tmp/rubocop_cache
  - &attach_workspace
    attach_workspace:
      at: ~/webpagewatcher
  - &persist_to_workspace
    persist_to_workspace:
      root: ~/webpagewatcher
      paths:
        - vendor/bundle
        - tmp/test-results
        - tmp/capybara
        - coverage

version: 2
jobs:
  git-checkout:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_checkout_cache
      - checkout
      - run: mkdir -p ~/webpagewatcher/tmp/test-results
      - *save_checkout_cache
      - *persist_to_workspace

  bundle-install:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_checkout_cache
      - *restore_bundle_cache
      - *bundle_path
      - *save_bundle_cache
      - *persist_to_workspace

  brakeman:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_checkout_cache
      - *restore_bundle_cache
      - *bundle_path
      - run: bundle exec brakeman --ensure-latest
      - *store_test_results
      - *persist_to_workspace

  rubocop:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_checkout_cache
      - *restore_bundle_cache
      - *bundle_path
      - *restore_rubocop_cache
      - run: mkdir -p ~/glados/tmp/test-results/rubocop
      - run: bundle exec rubocop -R -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb --format RuboCop::Formatter::JUnitFormatter --out ~/glados/tmp/test-results/rubocop/rubocop.xml
      - *save_rubocop_cache
      - *store_test_results
      - *persist_to_workspace

  bundler-audit:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_checkout_cache
      - *restore_bundle_cache
      - *bundle_path
      - run: bundle exec bundler-audit check --update
      - *store_test_results
      - *persist_to_workspace

workflows:
  version: 2

  ci-workflow:
    jobs:
      - git-checkout
      - bundle-install:
          requires:
            - git-checkout
      # - rspec:
      #     requires:
      #       - bundle-install
      - rubocop:
          requires:
            - bundle-install
      # - slim-lint:
      #     requires:
      #       - bundle-install
      - brakeman:
          requires:
            - bundle-install
      - bundler-audit:
          requires:
            - bundle-install
