default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: webpagewatcher_development

test:
  <<: *default
  database: <%= "webpagewatcher_test#{ENV['TEST_ENV_NUMBER']}" %>
  schema_search_path: 'public,local'

production: &production
  <<: *default
  database: <%= ENV['WPW_DATABASE_NAME'] %>
  username: <%= ENV['WPW_DATABASE_USER'] %>
  host: <%= ENV['WPW_DATABASE_HOST'] %>
  password: "<%= ENV['WPW_DATABASE_PASSWORD'] %>"
  pool: <%= ENV['WPW_DATABASE_POOL'] || 5 %>
  reaping_frequency: 10

staging:
  <<: *production
